# **1.1. IMPORTING DATASET**

In [26]:
import pandas as pd

In [27]:
ds=pd.read_csv(r"Crude_Oil_Prices.csv")

In [28]:
ds.shape

(2547, 2)

In [29]:
ds.head

<bound method NDFrame.head of             date   value
0     29-10-2012   85.54
1     30-10-2012   85.68
2     31-10-2012   86.24
3     01-11-2012   87.09
4     02-11-2012   84.86
...          ...     ...
2542  12-11-2022     NaN
2543  13-11-2022     NaN
2544  14-11-2022     NaN
2545  15-11-2022     NaN
2546  16-11-2022     NaN

[2547 rows x 2 columns]>

# **1.2. IMPORTING LIBRARIES**

In [30]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# **1.3. HANDLING_MISSING_VALUES**

In [31]:
ds.isnull().sum()


date       0
 value    21
dtype: int64

In [32]:
hd=ds.dropna()
print(hd)

            date   value
0     29-10-2012   85.54
1     30-10-2012   85.68
2     31-10-2012   86.24
3     01-11-2012   87.09
4     02-11-2012   84.86
...          ...     ...
2521  20-10-2022   85.98
2522  21-10-2022   85.05
2523  24-10-2022   84.92
2524  25-10-2022   84.79
2525  26-10-2022   88.05

[2526 rows x 2 columns]


In [33]:
hd.isnull().sum()

date      0
 value    0
dtype: int64

# **1.4. FEATURE_SCALING**

In [34]:
from sklearn import preprocessing

In [35]:
x = hd.iloc[:, 1:2].values
print ("\nOriginal data values : \n",  x)


Original data values : 
 [[85.54]
 [85.68]
 [86.24]
 ...
 [84.92]
 [84.79]
 [88.05]]


In [36]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))
x_after_min_max_scaler = min_max_scaler.fit_transform(x)
print ("\nAfter min max Scaling : \n", x_after_min_max_scaler)


After min max Scaling : 
 [[0.66062503]
 [0.66187012]
 [0.66685047]
 ...
 [0.65511108]
 [0.65395493]
 [0.68294765]]


In [37]:
Standardisation = preprocessing.StandardScaler()
x_after_Standardisation = Standardisation.fit_transform(x)
print ("\nAfter Standardisation : \n", x_after_Standardisation)


After Standardisation : 
 [[0.86576727]
 [0.87197137]
 [0.89678778]
 ...
 [0.83829196]
 [0.83253101]
 [0.97699794]]
